# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-06 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='post',
            new_name='posts',
        ),
    ]
