# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-06 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_auto_20190906_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='posts',
            new_name='project_posts',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_link',
            new_name='project_url',
        ),
    ]
