# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0004_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='Rates',
        ),
    ]
