# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_auto_20190908_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_url',
            new_name='url',
        ),
    ]
