# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-09 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_auto_20190908_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='project_url',
        ),
    ]
